### ISSUE TITLE
NDVI calculation

### ISSUE THREAD

**Issue by jgomezd** [jdbcode/LLR-LandTrendr#1]
Hi,

I was looking for your LandTrendr.js code and notice that in the lines 386-393, when you calculate NDVI:
// NDVI
var ndviTransform = function(img){ 
  var ndvi = img.normalizedDifference(['B4', 'B3']) // calculate normalized dif between band 4 and band 3 (B4-B3/B4_B3)
                .multiply(1000) // scale results by 1000
                .select([0], ['NDVI']) // name the band
                .set('system:time_start', img.get('system:time_start'));
  return ndvi;
};

You are using band 4 and band 3. Which are not the correct. You should use Band 5 and 4 according to the formula.

Bestm

**Comment by jdbcode** [comment]
Hi @jgomezd I believe this issue is intended for the https://github.com/eMapR/LT-GEE repo, not https://github.com/jdbcode/LLR-LandTrendr.

In any case, the `LandTrendr.js` script make Landsat 8 OLI bands names consistent with Landsat 5/7 naming convention. See line:
https://github.com/eMapR/LT-GEE/blob/de1f5f4c3bcf4c90872bafda584318e98f34ee75/LandTrendr.js#L44
